#!/usr/bin/env python3.11
from sys import argv, exit


match argv[1]:
    case "aur":
        print("""
      paru <target> -- Interactively search and install <target>.

      paru -- Alias for paru -Syu.

      paru -S <target> -- Install a specific package.

      paru -Sua -- Upgrade AUR packages.

      paru -Qua -- Print available AUR updates.

      paru -G <target> -- Download the PKGBUILD and related files of <target>.

      paru -Gp <target> -- Print the PKGBUILD of <target>.

      paru -Gc <target> -- Print the AUR comments of <target>.

      paru --gendb -- Generate the devel database for tracking *-git packages.
      This is only needed when you initially start using paru.

      paru -Ui -- Build and install a PKGBUILD in the current directory.
              """)
    case "ls":
        print("""
              Display options

    -1, --oneline: display one entry per line
    -G, --grid: display entries as a grid (default)
    -l, --long: display extended details and attributes
    -R, --recurse: recurse into directories
    -T, --tree: recurse into directories as a tree
    -x, --across: sort the grid across, rather than downwards
    -F, --classify: display type indicator by file names
    --colo[u]r: when to use terminal colours
    --colo[u]r-scale: highlight levels of file sizes distinctly
    --icons: display icons
    --no-icons: don't display icons (always overrides --icons)


              Filtering options

    -a, --all: show hidden and 'dot' files
    -d, --list-dirs: list directories like regular files
    -L, --level=(depth): limit the depth of recursion
    -r, --reverse: reverse the sort order
    -s, --sort=(field): which field to sort by
    --group-directories-first: list directories before other files
    -D, --only-dirs: list only directories
    --git-ignore: ignore files mentioned in .gitignore
    -I, --ignore-glob=(globs): glob patterns (pipe-separated) of files to ignore

Pass the --all option twice to also show the . and .. directories.

              Long view options
These options are available when running with --long (-l):

    -b, --binary: list file sizes with binary prefixes
    -B, --bytes: list file sizes in bytes, without any prefixes
    -g, --group: list each file’s group
    -h, --header: add a header row to each column
    -H, --links: list each file’s number of hard links
    -i, --inode: list each file’s inode number
    -m, --modified: use the modified timestamp field
    -S, --blocks: list each file’s number of file system blocks
    -t, --time=(field): which timestamp field to use
    -u, --accessed: use the accessed timestamp field
    -U, --created: use the created timestamp field
    -@, --extended: list each file’s extended attributes and sizes
    --changed: use the changed timestamp field
    --git: list each file’s Git status, if tracked or ignored
    --time-style: how to format timestamps
    --no-permissions: suppress the permissions field
    --octal-permissions: list each file's permission in octal format
    --no-filesize: suppress the filesize field
    --no-user: suppress the user field
    --no-time: suppress the time field
""")
    case _:
        exit()
