#!/usr/bin/env python3.11

from sys import argv

index = 0
with open('/home/rozhelluk/.config/alacritty/alacritty.yml', 'r') as file:
    data = file.readlines()
    for line in range(len(data)):
        if 'opacity:' in data[line]:
            index = line
            print(data[line].strip())

if len(argv) == 2:
    try:
        float(argv[1])
        data[index] = f'  opacity: {argv[1]}\n'
        with open('/home/rozhelluk/.config/alacritty/alacritty.yml', 'w') as file:
            file.writelines(data)
        exit()
    except BaseException as ex:
        print(ex)
else:
    if float(data[index].strip().split()[1]) != 1:
        data[index] = f'  opacity: 1\n'
        with open('/home/rozhelluk/.config/alacritty/alacritty.yml', 'w') as file:
            file.writelines(data)
        exit()

    data[index] = f'  opacity: 0\n'
    with open('/home/rozhelluk/.config/alacritty/alacritty.yml', 'w') as file:
        file.writelines(data)
