#!/usr/bin/env python3.11

from sys import argv

index = -1
with open('/home/rozhelluk/.config/alacritty/alacritty.yml', 'r') as file:
    config = file.readlines()
    for line in range(len(config)):
        if 'opacity:' in config[line]:
            index = line
            print(config[line].strip())


if len(argv) == 1:
    if float(config[index].strip().split()[1]) != 1:
        config[index] = f'  opacity: 1\n'
    else:
        config[index] = f'  opacity: 0\n'
try:
    if float(argv[1]) <= 1 and 0 <= float(argv[1]):
        config[index] = f'  opacity: {argv[1]}\n'
except:
    pass

with open('/home/rozhelluk/.config/alacritty/alacritty.yml', 'w') as file:
    file.writelines(config)
