#!/usr/bin/env python3


index = None
with open('/home/rozhelluk/.config/alacritty/alacritty.yml', 'r') as file:
    data = file.readlines()
    for line in range(len(data)):
        if 'decorations:' in data[line]:
            index = line
            print(data[line].strip())

if data[index].strip().split()[1] != "Full":
    data[index] = f'  decorations: Full\n'
    with open('/home/rozhelluk/.config/alacritty/alacritty.yml', 'w') as file:
        file.writelines(data)

else:
    data[index] = f'  decorations: None\n'
    with open('/home/rozhelluk/.config/alacritty/alacritty.yml', 'w') as file:
        file.writelines(data)
