#!/usr/bin/env python3.10


index = None
with open('/home/rozhelluk/.config/alacritty/alacritty.yml', 'r') as file:
    data = file.readlines()
    for line in range(len(data)):
        if 'opacity:' in data[line]:
            index = line
            print(data[line].strip())

if float(data[index].strip().split()[1]) != 1:
    data[index] = f'  opacity: 1\n'
    with open('/home/rozhelluk/.config/alacritty/alacritty.yml', 'w') as file:
        file.writelines(data)

else:
    data[index] = f'  opacity: 0\n'
    with open('/home/rozhelluk/.config/alacritty/alacritty.yml', 'w') as file:
        file.writelines(data)
